project/Clase/urls.py
from django.urls import path

app_name = "Clase"

urlpatterns = [
    #path
]

project/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("core.urls")),
    path("Clase/", include("Clase.urls"))
]

project/core/urls.py
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path("",views.home, name="home"),
]

project/Clase/models.py
from django.db import models

class Curso(models.Model):
    nombre = models.CharField(max_length=100)
    
    def __str__(self) -> str:
        return self.nombre   

class Estudiante(models.Model):
    nombre = models.CharField(max_length=200)
    curso = models.ForeignKey(Curso, on_delete=models.SET_NULL, null=True, blank=True)
    
    def __str__(self) -> str:
        return self.nombre 
    
class Profesor(models.Model):
    nombre = models.CharField(max_length=200)
    curso = models.ForeignKey(Curso, on_delete=models.SET_NULL, null= True, blank=True)

    def __str__(self) -> str:
        return self.nombre 
    
class Comision(models.Model):
    nombre = models.PositiveIntegerField(unique=True)
    curso = models.ForeignKey(Curso, on_delete=models.SET_NULL, null= True, blank=True)   
    profesor = models.ForeignKey(Profesor, on_delete=models.SET_NULL, null= True, blank=True)
    estudiante = models.ManyToManyField(Estudiante)
    
    def __str__(self) -> str:
        return self.nombre 
    

project/core/models.py
from django.db import models

# Create your models here.

project/Clase/views.py
from django.shortcuts import render

from . import models
# Create your views here.

def home(request):
    query = models.Comision.objects.all()
    context = {"comisiones":query}
    return render(request, "Clase/index.html", context)

project/core/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request, "core/index.html")

project/Clase/templates/Clase/index.html
{% extends 'core/base.html' %}

{% block title %}
    Comisiones
{% endblock title %}

{% block content %}
    
    {% for comision in comisiones %}

        <p>{{  comision  }}</p>
        
    {% endfor %}

{% endblock content %}

project/core/templates/core/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pre-Entrega N°3 - Paez Maximiliano</title>
</head>
<body>
    {% block title %}    
    {% endblock title %}

    {% block content %}        
    {% endblock content %}
</body>
</html>

project/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}
    <h1>Pagina Principal</h1>    
{% endblock title %}

{% block content %}
    <ul>
        <li>
            <a href="{% url 'Clase:home' %}">Clase</a>
        </li>
    </ul>        
{% endblock content %}